
title: Github Pages 예제
description: Github Pages 사용 예제 모음
logo: "assets/images/profile (200 x 200).png"
theme: jekyll-theme-minimal
lang: ko-KR
collections: 
  items:
    output: true
defaults:
  - scope:
      path: ""
      type: "items"
    values:
      layout: "item"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
comments:
  facebook:
    appid: 689649528577550
    num_posts: 10
    order_by: "reverse_time"
paginate: 2
paginate_path: "/blog/page:num/"  