title: Project ZZOM
description: 1인출판 프로젝트
logo: "assets/images/zzom-banner-light (1024 x 682).jpg"
theme: jekyll-theme-minimal
lang: ko-KR
collections: 
  books:
    output: true
defaults:
  - scope:
      path: ""
      type: "books"
    values:
      layout: "book"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
facebook:
  appid: 689649528577550
  comments_count: false
  num_posts: 10
  order_by: "reverse_time"
paginate: 5
paginate_path: "/blog/page:num/"
